import type { Metadata } from 'next';
import { Murecho } from 'next/font/google';
import '@/assets/scss/tailwind.scss';
import Navbar from '@/components/Navbar.Component';

const inter = Murecho({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#ebf0f5]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
